apiVersion: v1
kind: Service
metadata:
  name: amos-1
  labels:
    app: amos-1
    service: amos-1
    name: amos-1
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    statefulset.kubernetes.io/pod-name: amos-1
