apiVersion: v1
kind: Service
metadata:
  name: amos-0
  labels:
    app: amos-0
    service: amos-0
    name: amos-0
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: sshd
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    statefulset.kubernetes.io/pod-name: amos-0
