{{- if index .Values.archiveCron.enabled -}}
apiVersion: {{ .Capabilities.APIVersions.Has "batch/v1" | ternary "batch/v1" "batch/v1beta1" }}
kind: CronJob
metadata:
  name: {{ .Values.amos_logs_archive_cronjob.name }}
spec:
  schedule: "{{ .Values.archiveCron.scheduleMinute }} {{ .Values.archiveCron.scheduleHour }} */{{ .Values.archiveCron.executionDays }} * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 10800
      template:
        metadata:
        spec:
{{- if or .Values.nodeSelector .Values.global.nodeSelector }}
          nodeSelector:
{{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | indent 12 }}
{{- end }}
{{- if .Values.global.nodeSelector }}
{{ toYaml .Values.global.nodeSelector | indent 12 }}
{{- end }}
{{- end }}
{{- if include "eric-enmsg-amos-odp.pullSecrets" . }}
          imagePullSecrets:
            - name: {{ template "eric-enmsg-amos-odp.pullSecrets" . }}
{{- end }}
          containers:
            - name: {{ .Values.amos_logs_archive_cronjob.name }}
              image: {{ template "eric-enm-common-helmchart-library.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ index .Values "images" "eric-enm-amos-cronjobs" "name" }}:{{ index .Values "images" "eric-enm-amos-cronjobs" "tag" }}
              imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
              tty: {{ .Values.amos_logs_archive_cronjob.tty }}
              stdin: {{ .Values.amos_logs_archive_cronjob.stdin }}
{{- if .Values.amos_logs_archive_cronjob.command }}
              command: {{ .Values.amos_logs_archive_cronjob.command }}
{{- end }}
              args:
                - |
                  cd /ericsson/log/amos/
                  /home/shared/common/cronjob_files/archive_moshell_logs.sh /ericsson/log/amos/moshell_logfiles  --days {{ .Values.archiveCron.retentionPeriod }}
                  sleep 120
                  /home/shared/common/cronjob_files/clean_archived_logs.sh  --days {{ .Values.archiveCron.retentionPeriod }}
                  sleep 120
              resources:
                requests:
                  memory: 512Mi
                  cpu: 256m
                limits:
                  memory: 2Gi
                  cpu: 512m
{{- with .Values.amos_logs_archive_cronjob.volumeMounts }}
              volumeMounts:
{{ toYaml . | indent 16 }}
{{- end }}
{{- with .Values.amos_logs_archive_cronjob.volumes }}
          volumes:
{{ toYaml . | indent 10 }}
{{- end }}
          restartPolicy: {{ .Values.amos_logs_archive_cronjob.restartPolicy }}
{{- end }}