{{- define "eric-enmsg-amos.eric_ingress" -}}
metadata:
  name: amos-odp
spec:
  virtualServiceIP: {{ .Values.global.vips.amos_vip_address }}
{{- end}}
{{- if and .Values.global.tags.deploy_eric_net_ingress_l4 .Values.global.ip_version (or (eq .Values.global.ip_version "Dual") (eq .Values.global.ip_version "IPv4")) }}
{{- template "eric-enm-common-helmchart-library.eric_ingress" (list . "eric-enmsg-amos.eric_ingress") -}}
{{- end }}
